# Generated by Django 4.1 on 2022-09-20 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_reviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='comments',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='reviews',
            old_name='raring',
            new_name='rating',
        ),
    ]
